export const HANDLE_DRAWER_TOGGLE_CHANGE = "HANDLE_DRAWER_TOGGLE_CHANGE";

export const GET_FORM_REQUEST = "GET_FORM_REQUEST";
export const GET_FORM_SUCCESS = "GET_FORM_SUCCESS";
export const GET_FORM_FAILURE = "GET_FORM_FAILURE";

// Table Listing
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';


export const POST_USERS_REQUEST = 'POST_USERS_REQUEST';
export const POST_USERS_SUCCESS = 'POST_USERS_SUCCESS';
export const POST_USERS_FAILURE = 'POST_USERS_FAILURE';